// <auto-generated />
namespace FirstChoiceBooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FKChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FKChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201608062332045_FKChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
